b79_web_front:
  conf:
  - {dest: all, local: dnspod.py, remote: /web/b79_web_front/dnspod.py}
  - {dest: all, local: requirements.txt, remote: /web/b79_web_front/requirements.txt}
  exclude: ''
  hosts: [192.168.20.105]
  restart_cmd: /usr/bin/tomcat8b79webfront restart
  svn_path: svn://192.168.20.110/svn_project_code/dnsapi_flask
zip_test:
  conf:
  - {dest: all, local: menu.py, remote: /web/zip_test/menu.py}
  exclude_opts: ''
  hosts: [172.20.1.45, 172.20.1.63]
  info: zip_test
  restart_str: /usr/bin/tomcatziptest restart
  svn_path: svn://192.168.20.110/zip_test
